import { firstWordTree } from "../content/trees/first_word";
import { pastVerbTree } from "../content/trees/verb_past";
import { presentVerbTree } from "../content/trees/verb_present";
import { imperativeVerbTree } from "../content/trees/verb_imperative";
import { faelTree } from "../content/trees/fael";
import { mafoolTree } from "../content/trees/mafool";
import { tawabiTree } from "../content/trees/tawabi";
import { attachedPronounsTree } from "../content/trees/attached_pronouns";
import { ismManqousTree } from "../content/trees/ism_manqous";
import { firstWordExamples, firstWordCoverageKeysOrdered, firstWordQuizExamples } from "../content/examples/first_word.examples";
import { pastVerbExamples, pastVerbCoverageKeysOrdered, pastVerbQuizExamples } from "../content/examples/verb_past.examples";
import { presentVerbExamples, presentVerbCoverageKeysOrdered, presentVerbQuizExamples } from "../content/examples/verb_present.examples";
import { imperativeVerbExamples, imperativeVerbCoverageKeysOrdered, imperativeVerbQuizExamples } from "../content/examples/verb_imperative.examples";
import { faelExamples, faelCoverageKeysOrdered, faelQuizExamples } from "../content/examples/fael.examples";
import { mafoolExamples, mafoolCoverageKeysOrdered, mafoolQuizExamples } from "../content/examples/mafool.examples";
import {
  tawabiExamples,
  tawabiCoverageKeysOrdered,
  tawabiQuizExamples,
  tawabiNaatExamples,
  tawabiNaatCoverageKeysOrdered,
  tawabiNaatQuizExamples,
  tawabiAtfExamples,
  tawabiAtfCoverageKeysOrdered,
  tawabiAtfQuizExamples,
  tawabiTawkidExamples,
  tawabiTawkidCoverageKeysOrdered,
  tawabiTawkidQuizExamples,
  tawabiBadalExamples,
  tawabiBadalCoverageKeysOrdered,
  tawabiBadalQuizExamples,
} from "../content/examples/tawabi.examples";
import { attachedPronounsExamples, attachedPronounsCoverageKeysOrdered, attachedPronounsQuizExamples } from "../content/examples/attached_pronouns.examples";
import { ismManqousExamples, ismManqousCoverageKeysOrdered, ismManqousQuizExamples } from "../content/examples/ism_manqous.examples";
import { cleanMubtadaTree } from "../content/trees/clean_mubtada";
import { cleanKhabarTree } from "../content/trees/clean_khabar";
import { cleanKanaTree } from "../content/trees/clean_kana";
import { cleanInnaTree } from "../content/trees/clean_inna";

import {
  cleanMubtadaExamples,
  cleanMubtadaCoverageKeysOrdered,
  cleanMubtadaQuizExamples,
} from "../content/examples/clean_mubtada.examples";
import {
  cleanKhabarExamples,
  cleanKhabarCoverageKeysOrdered,
  cleanKhabarQuizExamples,
} from "../content/examples/clean_khabar.examples";
import {
  cleanKanaExamples,
  cleanKanaCoverageKeysOrdered,
  cleanKanaQuizExamples,
} from "../content/examples/clean_kana.examples";
import {
  cleanInnaExamples,
  cleanInnaCoverageKeysOrdered,
  cleanInnaQuizExamples,
} from "../content/examples/clean_inna.examples";

export const TOPICS = [
  {
    code: "first-word-key",
    name_ar: "مفتاح الكلمة الأولى",
    subtitle: "اسم / فعل / حرف مع الحفاظ على التسلسل الأول",
    shortLabel: "الكلمة الأولى",
    desc: "مسار يدرّب الطالب على بدء التفكير النحوي من نوع الكلمة الأولى قبل الإعراب.",
    tree: firstWordTree,
    examples: firstWordExamples,
    coverageKeysOrdered: firstWordCoverageKeysOrdered,
    quizExamples: firstWordQuizExamples,
    quizCoverageKeysOrdered: firstWordCoverageKeysOrdered,
    quizCount: Math.min(6, firstWordQuizExamples.length),
    level: 2,
    isReady: true,
  },
  {
    code: "past-verb",
    name_ar: "الفعل الماضي",
    subtitle: "الفتح / الضم / السكون مع إعراب الضمير المتصل",
    shortLabel: "الماضي",
    desc: "تدريب على بناء الفعل الماضي حسب اتصال الضمائر: واو الجماعة، ألف الاثنين، نون النسوة، وضمائر الرفع المتحركة.",
    tree: pastVerbTree,
    examples: pastVerbExamples,
    coverageKeysOrdered: pastVerbCoverageKeysOrdered,
    quizExamples: pastVerbQuizExamples,
    quizCoverageKeysOrdered: pastVerbCoverageKeysOrdered,
    quizCount: Math.min(8, pastVerbQuizExamples.length),
    level: 2,
    isReady: true,
  },
  {
    code: "present-verb",
    name_ar: "الفعل المضارع",
    subtitle: "نون النسوة / نون التوكيد / الأداة / الأفعال الخمسة / صحيح ومعتل الآخر",
    shortLabel: "المضارع",
    desc: "خوارزمية المضارع: نبدأ بنوع الكلمة وزمن الفعل، ثم نحدد هل المضارع مبني بنون النسوة أو نون التوكيد، أو معرب فنفحص الناصب والجازم، ثم نميز الصحيح والمعتل والأفعال الخمسة.",
    tree: presentVerbTree,
    examples: presentVerbExamples,
    coverageKeysOrdered: presentVerbCoverageKeysOrdered,
    quizExamples: presentVerbQuizExamples,
    quizCoverageKeysOrdered: presentVerbCoverageKeysOrdered,
    quizCount: Math.min(12, presentVerbQuizExamples.length),
    level: 2,
    isReady: true,
  },
  {
    code: "imperative-verb",
    name_ar: "فعل الأمر",
    subtitle: "حذف النون / حذف حرف العلة / السكون",
    shortLabel: "الأمر",
    desc: "مسار فعل الأمر دون خلطه بالمضارع: نلاحظ اتصال واو الجماعة أو ياء المخاطبة أو ألف الاثنين، ثم نرجع للأصل عند المعتل.",
    tree: imperativeVerbTree,
    examples: imperativeVerbExamples,
    coverageKeysOrdered: imperativeVerbCoverageKeysOrdered,
    quizExamples: imperativeVerbQuizExamples,
    quizCoverageKeysOrdered: imperativeVerbCoverageKeysOrdered,
    quizCount: Math.min(8, imperativeVerbQuizExamples.length),
    level: 2,
    isReady: true,
  },
  {
    code: "fael",
    name_ar: "الفاعل",
    subtitle: "فاعل مرفوع أو مبني في محل رفع",
    shortLabel: "الفاعل",
    desc: "تحديد نوع الفاعل أولًا ثم الوصول إلى علامة الرفع أو محل الرفع.",
    tree: faelTree,
    examples: faelExamples,
    coverageKeysOrdered: faelCoverageKeysOrdered,
    quizExamples: faelQuizExamples,
    quizCoverageKeysOrdered: faelCoverageKeysOrdered,
    quizCount: Math.min(21, faelQuizExamples.length),
    level: 2,
    isReady: true,
  },
  {
    code: "mafool-bih",
    name_ar: "المفعول به",
    subtitle: "مفعول به منصوب أو مبني في محل نصب",
    shortLabel: "المفعول به",
    desc: "تحديد نوع المفعول به أولًا ثم الوصول إلى علامة النصب أو محل النصب.",
    tree: mafoolTree,
    examples: mafoolExamples,
    coverageKeysOrdered: mafoolCoverageKeysOrdered,
    quizExamples: mafoolQuizExamples,
    quizCoverageKeysOrdered: mafoolCoverageKeysOrdered,
    quizCount: Math.min(14, mafoolQuizExamples.length),
    level: 2,
    isReady: true,
  },

  {
    code: "tawabi-naat",
    name_ar: "النعت",
    subtitle: "تمييز النعت عن الخبر والإضافة ثم إتباع المنعوت",
    shortLabel: "النعت",
    desc: "فرع من باب التوابع يدرّب الطالب على أن النعت يصف اسمًا قبله ويتبعه في الإعراب والتعريف والتنكير والنوع والعدد.",
    tree: tawabiTree,
    examples: tawabiNaatExamples,
    coverageKeysOrdered: tawabiNaatCoverageKeysOrdered,
    quizExamples: tawabiNaatQuizExamples,
    quizCoverageKeysOrdered: tawabiNaatCoverageKeysOrdered,
    quizCount: Math.min(8, tawabiNaatQuizExamples.length),
    level: 2,
    isReady: true,
  },
  {
    code: "tawabi-atf",
    name_ar: "العطف",
    subtitle: "حروف العطف ومشاركة المعطوف عليه في الحكم والإعراب",
    shortLabel: "العطف",
    desc: "فرع من باب التوابع يدرّب الطالب على أن المعطوف يأتي بعد حرف عطف ويشارك ما قبله في الحكم ويتبعه في الإعراب.",
    tree: tawabiTree,
    examples: tawabiAtfExamples,
    coverageKeysOrdered: tawabiAtfCoverageKeysOrdered,
    quizExamples: tawabiAtfQuizExamples,
    quizCoverageKeysOrdered: tawabiAtfCoverageKeysOrdered,
    quizCount: Math.min(8, tawabiAtfQuizExamples.length),
    level: 2,
    isReady: true,
  },
  {
    code: "tawabi-tawkid",
    name_ar: "التوكيد",
    subtitle: "اكتشاف التوكيد اللفظي والمعنوي دون إطالة المسار",
    shortLabel: "التوكيد",
    desc: "فرع من باب التوابع يدرّب الطالب على أن التوكيد يقوّي ما قبله، ثم يميّز سريعًا بين التوكيد اللفظي بتكرار اللفظ والتوكيد المعنوي بألفاظه المشهورة.",
    tree: tawabiTree,
    examples: tawabiTawkidExamples,
    coverageKeysOrdered: tawabiTawkidCoverageKeysOrdered,
    quizExamples: tawabiTawkidQuizExamples,
    quizCoverageKeysOrdered: tawabiTawkidCoverageKeysOrdered,
    quizCount: Math.min(6, tawabiTawkidQuizExamples.length),
    level: 2,
    isReady: true,
  },
  {
    code: "tawabi-badal",
    name_ar: "البدل",
    subtitle: "البدل والمبدل منه وأنواع البدل الأساسية",
    shortLabel: "البدل",
    desc: "فرع من باب التوابع يدرّب الطالب على أن البدل يوضح المقصود من الاسم السابق ويمكن غالبًا أن يحل محله.",
    tree: tawabiTree,
    examples: tawabiBadalExamples,
    coverageKeysOrdered: tawabiBadalCoverageKeysOrdered,
    quizExamples: tawabiBadalQuizExamples,
    quizCoverageKeysOrdered: tawabiBadalCoverageKeysOrdered,
    quizCount: Math.min(6, tawabiBadalQuizExamples.length),
    level: 2,
    isReady: true,
  },
  {
    code: "tawabi",
    name_ar: "التوابع — تدريب مختلط",
    subtitle: "تمييز النعت، العطف، التوكيد، والبدل في مسار واحد",
    shortLabel: "التدريب المختلط",
    desc: "مسار يدرّب الطالب على اكتشاف العلاقة بالمعنى أولًا، ثم تسمية التابع، ثم إتباع المتبوع في الرفع أو النصب أو الجر مع اختيار العلامة المناسبة.",
    tree: tawabiTree,
    examples: tawabiExamples,
    coverageKeysOrdered: tawabiCoverageKeysOrdered,
    quizExamples: tawabiQuizExamples,
    quizCoverageKeysOrdered: tawabiCoverageKeysOrdered,
    quizCount: Math.min(12, tawabiQuizExamples.length),
    level: 2,
    isReady: true,
  },
  {
    code: "attached-pronouns",
    name_ar: "الضمائر المتصلة والمنفصلة",
    subtitle: "ضمائر الرفع والنصب والجر بحسب محل الاسم الذي تنوب عنه",
    shortLabel: "الضمائر",
    desc: "يتعلم الطالب أن الضمير يأخذ محل الاسم الذي ناب عنه: رفعًا أو نصبًا أو جرًا، مع التمييز بين المتصل والمنفصل.",
    tree: attachedPronounsTree,
    examples: attachedPronounsExamples,
    coverageKeysOrdered: attachedPronounsCoverageKeysOrdered,
    quizExamples: attachedPronounsQuizExamples,
    quizCoverageKeysOrdered: attachedPronounsCoverageKeysOrdered,
    quizCount: Math.min(8, attachedPronounsQuizExamples.length),
    level: 2,
    isReady: true,
  },
  {
    code: "ism-manqous",
    name_ar: "الاسم المنقوص",
    subtitle: "بقاء الياء أو حذفها حسب النصب والرفع والجر",
    shortLabel: "الاسم المنقوص",
    desc: "شجرة مبسطة لحل مشكلة الاسم المنقوص: نبدأ بالموقع الإعرابي ثم نحدد بقاء الياء أو حذفها.",
    tree: ismManqousTree,
    examples: ismManqousExamples,
    coverageKeysOrdered: ismManqousCoverageKeysOrdered,
    quizExamples: ismManqousQuizExamples,
    quizCoverageKeysOrdered: ismManqousCoverageKeysOrdered,
    quizCount: Math.min(8, ismManqousQuizExamples.length),
    level: 2,
    isReady: true,
  },
  {
    code: "nominal-advanced",
    name_ar: "الجملة الاسمية",
    subtitle: "مسار المبتدأ — شجرة نظيفة قابلة للتوسعة",
    shortLabel: "المبتدأ",
    slogan: "مدرّب تفكير نحوي موجّه",
    desc: "تعلّم مسار المبتدأ: الاسم المعرب، الاسم المبني، والمصدر المؤول مع صياغة إعراب ثابتة.",
    tree: cleanMubtadaTree,
    examples: cleanMubtadaExamples,
    coverageKeysOrdered: cleanMubtadaCoverageKeysOrdered,
    quizExamples: cleanMubtadaQuizExamples,
    quizCoverageKeysOrdered: cleanMubtadaCoverageKeysOrdered,
    quizCount: Math.min(12, cleanMubtadaQuizExamples.length),
    level: 2,
    isReady: true,
  },
  {
    code: "khabar",
    name_ar: "الخبر",
    subtitle: "خبر مفرد، جملة، وشبه جملة",
    shortLabel: "الخبر",
    desc: "مسارات الخبر المفرد والجملة وشبه الجملة، مع تحديد نوع الاسم المبني قبل الإعراب.",
    tree: cleanKhabarTree,
    examples: cleanKhabarExamples,
    coverageKeysOrdered: cleanKhabarCoverageKeysOrdered,
    quizExamples: cleanKhabarQuizExamples,
    quizCoverageKeysOrdered: cleanKhabarCoverageKeysOrdered,
    quizCount: Math.min(12, cleanKhabarQuizExamples.length),
    level: 2,
    isReady: true,
  },
  {
    code: "kana-wa-akhawatuha",
    name_ar: "كان وأخواتها",
    subtitle: "اسم كان مرفوع وخبر كان منصوب",
    shortLabel: "كان وأخواتها",
    desc: "نفس منطق الجملة الاسمية بعد دخول كان: اسم كان مرفوع وخبر كان منصوب.",
    tree: cleanKanaTree,
    examples: cleanKanaExamples,
    coverageKeysOrdered: cleanKanaCoverageKeysOrdered,
    quizExamples: cleanKanaQuizExamples,
    quizCoverageKeysOrdered: cleanKanaCoverageKeysOrdered,
    quizCount: Math.min(10, cleanKanaQuizExamples.length),
    level: 2,
    isReady: true,
  },
  {
    code: "inna-wa-akhawatuha",
    name_ar: "إن وأخواتها",
    subtitle: "اسم إن منصوب وخبر إن مرفوع",
    shortLabel: "إن وأخواتها",
    desc: "نفس منطق الجملة الاسمية بعد دخول إن: اسم إن منصوب وخبر إن مرفوع.",
    tree: cleanInnaTree,
    examples: cleanInnaExamples,
    coverageKeysOrdered: cleanInnaCoverageKeysOrdered,
    quizExamples: cleanInnaQuizExamples,
    quizCoverageKeysOrdered: cleanInnaCoverageKeysOrdered,
    quizCount: Math.min(10, cleanInnaQuizExamples.length),
    level: 2,
    isReady: true,
  },
];

export function getTopicByCode(code) {
  return TOPICS.find((topic) => topic.code === code) ?? null;
}

export function getReadyTopics() {
  return TOPICS.filter((topic) => topic.isReady);
}

export function getTopicRoutes(code) {
  return {
    topics: `/paths?topic=${code}`,
    paths: `/paths?topic=${code}`,
    learn: `/learn/${code}`,
    practice: `/train/${code}`,
    quiz: `/quiz/${code}`,
    dashboard: "/dashboard",
  };
}
