export type ExerciseTree = { startNodeId: string; nodes: Record<string, any> };

export const mafoolTree: ExerciseTree = {
  startNodeId: "mafool_relation",
  nodes: {
    mafool_relation: { id: "mafool_relation", type: "question", context: "بعد معرفة الفعل والفاعل نسأل عن أثر الفعل.", text: "هل وقع فعل الفاعل على الكلمة المحددة؟", hint: "المفعول به هو ما وقع عليه فعل الفاعل.", answers: [ { id: "a", text: "نعم، وقع عليها الفعل", next: "mafool_start", eval: { fact: "relation", equals: "object" } }, { id: "b", text: "لا، هي التي فعلت الفعل", next: "mafool_relation", correct: false, hint: "هذه صفة الفاعل، لا المفعول به." }, { id: "c", text: "لا علاقة لها بالفعل", next: "mafool_relation", correct: false, hint: "اسأل: ماذا قرأ؟ ماذا أكرم؟ على من وقع الفعل؟" } ] },
    mafool_start: { id: "mafool_start", type: "question", context: "عرفنا أنها مفعول به. المفعول به حكمه النصب، لكن نحتاج نوعه لنحدد العلامة أو المحل.", text: "ما صورة المفعول به؟", hint: "قد يكون اسمًا معربًا، اسمًا مبنيًا، أو مصدرًا مؤولًا.", answers: [ { id: "a", text: "اسم معرب", next: "mafool_number", eval: { fact: "nounKind", equals: "mu3rab" } }, { id: "b", text: "اسم مبني", next: "mafool_built", eval: { fact: "nounKind", equals: "mabni" } }, { id: "c", text: "مصدر مؤول", next: "R_mafool_masdar", eval: { fact: "nounKind", equals: "masdar" } } ] },
    mafool_built: { id: "mafool_built", type: "question", context: "الاسم المبني لا تظهر عليه علامة النصب، فنقول: في محل نصب.", text: "ما نوع الاسم المبني؟", hint: "مثل: ضمير، اسم إشارة، اسم موصول.", answers: [ { id: "a", text: "ضمير", next: "R_mafool_damir", eval: { fact: "mabniType", equals: "damir" } }, { id: "b", text: "اسم إشارة", next: "R_mafool_ishara", eval: { fact: "mabniType", equals: "ishara" } }, { id: "c", text: "اسم موصول", next: "R_mafool_mawsool", eval: { fact: "mabniType", equals: "mawsool" } }, { id: "d", text: "اسم استفهام", next: "R_mafool_istifham", eval: { fact: "mabniType", equals: "istifham" } }, { id: "e", text: "اسم شرط", next: "R_mafool_shart", eval: { fact: "mabniType", equals: "shart" } }, { id: "f", text: "كم الخبرية", next: "R_mafool_kam", eval: { fact: "mabniType", equals: "kam" } } ] },
    mafool_number: { id: "mafool_number", type: "question", context: "الاسم المعرب تتغير علامته حسب موقعه. هنا موقعه مفعول به، إذن نبحث عن علامة النصب.", text: "ما نوع الاسم المعرب؟", hint: "النوع يقودنا إلى علامة النصب.", answers: [ { id: "a", text: "مفرد أو جمع تكسير", next: "mafool_ending", eval: { fact: "number", equals: "singular" } }, { id: "b", text: "مثنى", next: "R_mafool_dual", eval: { fact: "number", equals: "dual" } }, { id: "c", text: "جمع مذكر سالم", next: "R_mafool_jms", eval: { fact: "number", equals: "jms" } }, { id: "d", text: "جمع مؤنث سالم", next: "R_mafool_jfs", eval: { fact: "number", equals: "jfs" } }, { id: "e", text: "جمع تكسير", next: "mafool_ending", eval: { fact: "number", equals: "jt" } }, { id: "f", text: "من الأسماء الخمسة", next: "R_mafool_five", eval: { fact: "number", equals: "five" } } ] },
    mafool_ending: { id: "mafool_ending", type: "question", context: "المفرد وجمع التكسير ينصبان غالبًا بالفتحة؛ نحدد هل تظهر أو تقدر.", text: "هل آخر الاسم صحيح أم معتل؟", hint: "الصحيح تظهر عليه الفتحة، والمعتل قد تقدر عليه.", answers: [ { id: "a", text: "صحيح الآخر", next: "R_mafool_visible", eval: { fact: "ending", equals: "sahih" } }, { id: "b", text: "معتل الآخر", next: "R_mafool_estimated", eval: { fact: "ending", equals: "moatal" } } ] },
    R_mafool_visible: { id: "R_mafool_visible", type: "result", coverage: "mafool.visible", text: "مفعول به منصوب وعلامة نصبه الفتحة الظاهرة على آخره." },
    R_mafool_estimated: { id: "R_mafool_estimated", type: "result", coverage: "mafool.estimated", text: "مفعول به منصوب وعلامة نصبه الفتحة المقدرة على آخره." },
    R_mafool_dual: { id: "R_mafool_dual", type: "result", coverage: "mafool.dual", text: "مفعول به منصوب وعلامة نصبه الياء لأنه مثنى." },
    R_mafool_jms: { id: "R_mafool_jms", type: "result", coverage: "mafool.jms", text: "مفعول به منصوب وعلامة نصبه الياء لأنه جمع مذكر سالم." },
    R_mafool_jfs: { id: "R_mafool_jfs", type: "result", coverage: "mafool.jfs", text: "مفعول به منصوب وعلامة نصبه الكسرة نيابة عن الفتحة لأنه جمع مؤنث سالم." },
    R_mafool_five: { id: "R_mafool_five", type: "result", coverage: "mafool.five", text: "مفعول به منصوب وعلامة نصبه الألف لأنه من الأسماء الخمسة." },
    R_mafool_damir: { id: "R_mafool_damir", type: "result", coverage: "mafool.pronoun", text: "ضمير مبني في محل نصب مفعول به." },
    R_mafool_ishara: { id: "R_mafool_ishara", type: "result", coverage: "mafool.ishara", text: "اسم إشارة مبني في محل نصب مفعول به." },
    R_mafool_mawsool: { id: "R_mafool_mawsool", type: "result", coverage: "mafool.mawsool", text: "اسم موصول مبني في محل نصب مفعول به." },
    R_mafool_istifham: { id: "R_mafool_istifham", type: "result", coverage: "mafool.istifham", text: "اسم استفهام مبني في محل نصب مفعول به." },
    R_mafool_shart: { id: "R_mafool_shart", type: "result", coverage: "mafool.shart", text: "اسم شرط مبني في محل نصب مفعول به." },
    R_mafool_kam: { id: "R_mafool_kam", type: "result", coverage: "mafool.kam", text: "كم الخبرية مبنية في محل نصب مفعول به." },
    R_mafool_masdar: { id: "R_mafool_masdar", type: "result", coverage: "mafool.masdar", text: "مصدر مؤول في محل نصب مفعول به." }
  }
};
