export type ExerciseTree = { startNodeId: string; nodes: Record<string, any> };

export const imperativeVerbTree: ExerciseTree = {
  startNodeId: "imp_step_1",
  nodes: {
    imp_step_1: { id: "imp_step_1", type: "question", context: "لنبدأ من الكلمة التي تحتها خط: هل هي طلب من المخاطب؟", text: "هل تطلب هذه الكلمة من المخاطب أن يفعل شيئًا؟", hint: "فعل الأمر يطلب من المخاطب أن يفعل شيئًا.", answers: [ { id: "a", text: "نعم، يدل على طلب", next: "imp_attached_check", correct: true }, { id: "b", text: "لا، يدل على حدث ماضٍ", next: "imp_step_1", correct: false, hint: "الماضي يخبر عن حدث انتهى، ولا يطلب فعلًا." }, { id: "c", text: "لا، يدل على حاضر أو مستقبل", next: "imp_step_1", correct: false, hint: "المضارع يدل على الحاضر أو المستقبل، أما الأمر فهو طلب." } ] },
    imp_attached_check: { id: "imp_attached_check", type: "question", context: "عرفنا أنها طلب؛ الآن نفحص آخر الفعل واتصاله.", text: "هل اتصل بواو الجماعة أو ألف الاثنين أو ياء المخاطبة؟", hint: "إذا اتصل بأحدها يكون بناء الأمر على حذف النون.", answers: [ { id: "a", text: "نعم، اتصل بأحدها", next: "imp_attached_type", eval: { fact: "attachedGroup", equals: "yes" } }, { id: "b", text: "لا، لم يتصل بأحدها", next: "imp_ending", eval: { fact: "attachedGroup", equals: "no" } } ] },
    imp_attached_type: { id: "imp_attached_type", type: "question", context: "الاتصال هنا يقودنا إلى علامة البناء.", text: "ما الضمير المتصل بالفعل؟", hint: "نختار الضمير المتصل، ثم يبني النظام النتيجة.", answers: [ { id: "a", text: "واو الجماعة", next: "R_imperative_delete_noon_waw", eval: { fact: "attached", equals: "waw" } }, { id: "b", text: "ياء المخاطبة", next: "R_imperative_delete_noon_yaa", eval: { fact: "attached", equals: "yaa" } }, { id: "c", text: "ألف الاثنين", next: "R_imperative_delete_noon_alif2", eval: { fact: "attached", equals: "alif2" } } ] },
    imp_ending: { id: "imp_ending", type: "question", context: "لم يتصل الفعل بهذه الضمائر؛ نرجع إلى آخر الفعل.", text: "هل آخره صحيح أم معتل؟", hint: "صحيح الآخر يبنى على السكون، ومعتل الآخر يبنى على حذف حرف العلة.", answers: [ { id: "a", text: "صحيح الآخر", next: "R_imperative_sukoon", eval: { fact: "ending", equals: "sahih" } }, { id: "b", text: "معتل الآخر", next: "R_imperative_delete_letter", eval: { fact: "ending", equals: "weak" } } ] },
    R_imperative_delete_noon_waw: { id: "R_imperative_delete_noon_waw", type: "result", coverage: "imperative.delete_noon.waw", text: "فعل أمر مبني على حذف النون لاتصاله بواو الجماعة، وواو الجماعة ضمير متصل مبني في محل رفع فاعل." },
    R_imperative_delete_noon_yaa: { id: "R_imperative_delete_noon_yaa", type: "result", coverage: "imperative.delete_noon.yaa", text: "فعل أمر مبني على حذف النون لاتصاله بياء المخاطبة، وياء المخاطبة ضمير متصل مبني في محل رفع فاعل." },
    R_imperative_delete_noon_alif2: { id: "R_imperative_delete_noon_alif2", type: "result", coverage: "imperative.delete_noon.alif2", text: "فعل أمر مبني على حذف النون لاتصاله بألف الاثنين، وألف الاثنين ضمير متصل مبني في محل رفع فاعل." },
    R_imperative_delete_letter: { id: "R_imperative_delete_letter", type: "result", coverage: "imperative.delete_letter", text: "فعل أمر مبني على حذف حرف العلة من آخره." },
    R_imperative_sukoon: { id: "R_imperative_sukoon", type: "result", coverage: "imperative.sukoon", text: "فعل أمر مبني على السكون على آخره." }
  }
};
