import type { PlaceGameCycle } from "./model";

export const SchoolFoundationsCycle: PlaceGameCycle = {
    id: "school-foundations",
    title: "بوصلة البداية",
    theme: "المدرسة وأساسيات الموقع الإعرابي",
    challenges: [
      {
        id: "student-subject",
        topic: "الفاعل",
        skill: "الرفع بالضمة",
        word: "الطَّالِبُ",
        correctChoiceId: "subject",
        hint: "ابحث عن الجملة التي يكون فيها الطالب هو من قام بالفعل.",
        choices: [
          {
            id: "object",
            sentence: "كَرَّمَ المُعَلِّمُ {word}.",
            requiredForm: "الطَّالِبَ",
            role: "مفعول به منصوب",
            explanation: "فعل التكريم وقع على الطالب؛ فهو مفعول به منصوب، ولذلك تحتاج الجملة «الطَّالِبَ» بالفتحة.",
          },
          {
            id: "subject",
            sentence: "حَضَرَ {word} مُبَكِّرًا.",
            requiredForm: "الطَّالِبُ",
            role: "فاعل مرفوع",
            explanation: "الطالب هو الذي قام بفعل الحضور؛ فهو فاعل مرفوع، وعلامة رفع الاسم المفرد الضمة.",
          },
          {
            id: "genitive",
            sentence: "سَلَّمْتُ عَلَى {word}.",
            requiredForm: "الطَّالِبِ",
            role: "اسم مجرور",
            explanation: "سبقت الكلمة بحرف الجر «على»؛ لذلك تحتاج الجملة «الطَّالِبِ» بالكسرة.",
          },
        ],
      },
      {
        id: "teacher-object",
        topic: "المفعول به",
        skill: "النصب بالفتحة",
        word: "المُعَلِّمَ",
        correctChoiceId: "object",
        hint: "ابحث عن الجملة التي وقع فيها الفعل على المعلّم.",
        choices: [
          {
            id: "subject",
            sentence: "وَصَلَ {word} إِلَى الفَصْلِ.",
            requiredForm: "المُعَلِّمُ",
            role: "فاعل مرفوع",
            explanation: "المعلّم هو الذي وصل؛ فهو فاعل مرفوع، وتحتاج الجملة «المُعَلِّمُ» بالضمة.",
          },
          {
            id: "object",
            sentence: "شَكَرَ الطَّالِبُ {word}.",
            requiredForm: "المُعَلِّمَ",
            role: "مفعول به منصوب",
            explanation: "وقع فعل الشكر على المعلّم؛ فهو مفعول به منصوب، وعلامة نصبه الفتحة.",
          },
          {
            id: "genitive",
            sentence: "اِسْتَمَعْتُ إِلَى {word}.",
            requiredForm: "المُعَلِّمِ",
            role: "اسم مجرور",
            explanation: "جاءت الكلمة بعد حرف الجر «إلى»؛ لذلك تحتاج الجملة «المُعَلِّمِ» بالكسرة.",
          },
        ],
      },
      {
        id: "school-genitive",
        topic: "الاسم المجرور",
        skill: "الجر بالكسرة",
        word: "المَدْرَسَةِ",
        correctChoiceId: "genitive",
        hint: "ابحث عن حرف جر يسبق الفراغ مباشرة.",
        choices: [
          {
            id: "subject",
            sentence: "{word} قَرِيبَةٌ مِنْ بَيْتِنَا.",
            requiredForm: "المَدْرَسَةُ",
            role: "مبتدأ مرفوع",
            explanation: "بدأت الجملة بالمدرسة وتحدثت عنها؛ فهي مبتدأ مرفوع، وتحتاج الجملة «المَدْرَسَةُ» بالضمة.",
          },
          {
            id: "object",
            sentence: "فَتَحَ المُدِيرُ {word} صَبَاحًا.",
            requiredForm: "المَدْرَسَةَ",
            role: "مفعول به منصوب",
            explanation: "وقع فعل الفتح على المدرسة؛ فهي مفعول به منصوب، وتحتاج الجملة «المَدْرَسَةَ» بالفتحة.",
          },
          {
            id: "genitive",
            sentence: "ذَهَبْتُ إِلَى {word} صَبَاحًا.",
            requiredForm: "المَدْرَسَةِ",
            role: "اسم مجرور",
            explanation: "سبقت الكلمة بحرف الجر «إلى»؛ فهي اسم مجرور، وعلامة جرها الكسرة.",
          },
        ],
      },
      {
        id: "diligent-predicate",
        topic: "الخبر",
        skill: "الخبر المرفوع",
        word: "مُجْتَهِدٌ",
        correctChoiceId: "predicate",
        hint: "ابحث عن جملة بدأت باسم وتحتاج كلمة تتمّ المعنى عنه.",
        choices: [
          {
            id: "predicate",
            sentence: "الطَّالِبُ {word}.",
            requiredForm: "مُجْتَهِدٌ",
            role: "خبر مرفوع",
            explanation: "الكلمة أخبرت عن الطالب وأتمّت معنى الجملة الاسمية؛ فهي خبر مرفوع بالضمة.",
          },
          {
            id: "accusative-adjective",
            sentence: "رَأَيْتُ طَالِبًا {word}.",
            requiredForm: "مُجْتَهِدًا",
            role: "نعت منصوب",
            explanation: "الكلمة تصف «طالبًا» المنصوب؛ والنعت يتبع منعوته، فتحتاج الجملة «مُجْتَهِدًا» بالفتحة.",
          },
          {
            id: "genitive-adjective",
            sentence: "مَرَرْتُ بِطَالِبٍ {word}.",
            requiredForm: "مُجْتَهِدٍ",
            role: "نعت مجرور",
            explanation: "الكلمة تصف «طالبٍ» المجرور؛ والنعت يتبع منعوته، فتحتاج الجملة «مُجْتَهِدٍ» بالكسرة.",
          },
        ],
      },
      {
        id: "writes-indicative",
        topic: "الفعل المضارع",
        skill: "الرفع بالضمة",
        word: "يَكْتُبُ",
        correctChoiceId: "indicative",
        hint: "ابحث عن المضارع الذي لم يسبقه ناصب ولا جازم.",
        choices: [
          {
            id: "subjunctive",
            sentence: "لَنْ {word} الطَّالِبُ الدَّرْسَ مُتَأَخِّرًا.",
            requiredForm: "يَكْتُبَ",
            role: "فعل مضارع منصوب",
            explanation: "سبق الفعلَ الحرفُ الناصب «لن»؛ لذلك تحتاج الجملة «يَكْتُبَ» بالفتحة.",
          },
          {
            id: "indicative",
            sentence: "الطَّالِبُ {word} الدَّرْسَ كُلَّ يَوْمٍ.",
            requiredForm: "يَكْتُبُ",
            role: "فعل مضارع مرفوع",
            explanation: "لم يسبق الفعل ناصب ولا جازم؛ فهو مضارع مرفوع، وعلامة رفعه الضمة الظاهرة.",
          },
          {
            id: "jussive",
            sentence: "لَمْ {word} الطَّالِبُ الدَّرْسَ أَمْسِ.",
            requiredForm: "يَكْتُبْ",
            role: "فعل مضارع مجزوم",
            explanation: "سبق الفعلَ الحرفُ الجازم «لم»؛ لذلك تحتاج الجملة «يَكْتُبْ» بالسكون.",
          },
        ],
      },
      {
        id: "father-five-nouns",
        topic: "الأسماء الخمسة",
        skill: "الرفع بالواو",
        word: "أَبُوكَ",
        correctChoiceId: "subject",
        hint: "اسأل: من الذي حضر؟ ثم تذكّر علامة رفع الأسماء الخمسة.",
        choices: [
          {
            id: "object",
            sentence: "قَابَلْتُ {word} عِنْدَ البَابِ.",
            requiredForm: "أَبَاكَ",
            role: "مفعول به منصوب",
            explanation: "وقع فعل المقابلة على الأب؛ فهو مفعول به منصوب، وعلامة نصب الأسماء الخمسة الألف: «أَبَاكَ».",
          },
          {
            id: "subject",
            sentence: "حَضَرَ {word} إِلَى المَدْرَسَةِ.",
            requiredForm: "أَبُوكَ",
            role: "فاعل مرفوع",
            explanation: "الأب هو الذي حضر؛ فهو فاعل مرفوع، وعلامة رفع الأسماء الخمسة الواو: «أَبُوكَ».",
          },
          {
            id: "genitive",
            sentence: "سَلَّمْتُ عَلَى {word}.",
            requiredForm: "أَبِيكَ",
            role: "اسم مجرور",
            explanation: "سبقت الكلمة بحرف الجر «على»؛ وعلامة جر الأسماء الخمسة الياء: «أَبِيكَ».",
          },
        ],
      },
      {
        id: "knowledge-first-word",
        topic: "الكلمة الأولى",
        skill: "المبتدأ المرفوع",
        word: "العِلْمُ",
        correctChoiceId: "starter",
        hint: "ابحث عن الجملة التي بدأت باسم نتحدث عنه.",
        choices: [
          {
            id: "starter",
            sentence: "{word} نُورٌ.",
            requiredForm: "العِلْمُ",
            role: "مبتدأ مرفوع",
            explanation: "بدأت الجملة باسم نتحدث عنه؛ فـ«العِلْمُ» مبتدأ مرفوع بالضمة.",
          },
          {
            id: "object",
            sentence: "طَلَبَ الطَّالِبُ {word}.",
            requiredForm: "العِلْمَ",
            role: "مفعول به منصوب",
            explanation: "وقع فعل الطلب على العلم؛ فهو مفعول به منصوب، وتحتاج الجملة «العِلْمَ» بالفتحة.",
          },
          {
            id: "genitive",
            sentence: "بَحَثَ الطَّالِبُ عَنِ {word}.",
            requiredForm: "العِلْمِ",
            role: "اسم مجرور",
            explanation: "سبقت الكلمة بحرف الجر «عن»؛ فتحتاج الجملة «العِلْمِ» بالكسرة.",
          },
        ],
      },
    ],
  };
