import type { PlaceGameCycle } from "./model";

export const DailyLifeCycle: PlaceGameCycle = {
    id: "daily-life",
    title: "جولة الحياة اليومية",
    theme: "المواقف اليومية وتثبيت الفروق الدقيقة",
    challenges: [
      {
        id: "guest-subject",
        topic: "الفاعل",
        skill: "الرفع بالضمة",
        word: "الضَّيْفُ",
        correctChoiceId: "subject",
        hint: "ابحث عن الجملة التي يكون فيها الضيف هو القادم.",
        choices: [
          {
            id: "object",
            sentence: "اِسْتَقْبَلَ الأَبُ {word}.",
            requiredForm: "الضَّيْفَ",
            role: "مفعول به منصوب",
            explanation: "وقع الاستقبال على الضيف؛ فتحتاج الجملة «الضَّيْفَ» بالفتحة.",
          },
          {
            id: "genitive",
            sentence: "رَحَّبْنَا بِـ{word}.",
            requiredForm: "الضَّيْفِ",
            role: "اسم مجرور",
            explanation: "سبقت الكلمة بالباء؛ فتحتاج الجملة «الضَّيْفِ» بالكسرة.",
          },
          {
            id: "subject",
            sentence: "وَصَلَ {word} فِي المَوْعِدِ.",
            requiredForm: "الضَّيْفُ",
            role: "فاعل مرفوع",
            explanation: "الضيف هو الذي وصل؛ فهو فاعل مرفوع بالضمة.",
          },
        ],
      },
      {
        id: "meal-object",
        topic: "المفعول به",
        skill: "النصب بالفتحة",
        word: "الوَجْبَةَ",
        correctChoiceId: "object",
        hint: "ابحث عن الجملة التي أعدّت فيها الأسرة الوجبة.",
        choices: [
          {
            id: "starter",
            sentence: "{word} جَاهِزَةٌ.",
            requiredForm: "الوَجْبَةُ",
            role: "مبتدأ مرفوع",
            explanation: "بدأت الجملة بالوجبة وتحدثت عنها؛ فتحتاج «الوَجْبَةُ» بالضمة.",
          },
          {
            id: "object",
            sentence: "أَعَدَّتِ الأُسْرَةُ {word}.",
            requiredForm: "الوَجْبَةَ",
            role: "مفعول به منصوب",
            explanation: "وقع فعل الإعداد على الوجبة؛ فهي مفعول به منصوب بالفتحة.",
          },
          {
            id: "genitive",
            sentence: "تَحَدَّثْنَا عَنِ {word}.",
            requiredForm: "الوَجْبَةِ",
            role: "اسم مجرور",
            explanation: "سبقت الكلمة بحرف الجر «عن»؛ فتحتاج الجملة «الوَجْبَةِ» بالكسرة.",
          },
        ],
      },
      {
        id: "road-safe",
        topic: "إن وأخواتها",
        skill: "خبر إن مرفوع",
        word: "آمِنٌ",
        correctChoiceId: "inna",
        hint: "بعد «إنَّ» يبقى الخبر مرفوعًا.",
        choices: [
          {
            id: "kana",
            sentence: "كَانَ الطَّرِيقُ {word}.",
            requiredForm: "آمِنًا",
            role: "خبر كان منصوب",
            explanation: "خبر «كان» منصوب؛ فتحتاج الجملة «آمِنًا» بالفتحة.",
          },
          {
            id: "inna",
            sentence: "إِنَّ الطَّرِيقَ {word}.",
            requiredForm: "آمِنٌ",
            role: "خبر إن مرفوع",
            explanation: "خبر «إنَّ» مرفوع؛ لذلك جاءت «آمِنٌ» بالضمة.",
          },
          {
            id: "became",
            sentence: "أَصْبَحَ الطَّرِيقُ {word}.",
            requiredForm: "آمِنًا",
            role: "خبر أصبح منصوب",
            explanation: "«أصبح» من أخوات كان وتنصب الخبر؛ فتحتاج الجملة «آمِنًا».",
          },
        ],
      },
      {
        id: "clean-adjective",
        topic: "النعت",
        skill: "التبعية في الإعراب",
        word: "النَّظِيفُ",
        correctChoiceId: "nominative",
        hint: "راقب حركة الاسم الموصوف «البيت».",
        choices: [
          {
            id: "accusative",
            sentence: "زُرْتُ البَيْتَ {word}.",
            requiredForm: "النَّظِيفَ",
            role: "نعت منصوب",
            explanation: "«النظيف» وصفٌ لـ«البيتَ» المنصوب؛ فتحتاج الجملة «النَّظِيفَ».",
          },
          {
            id: "genitive",
            sentence: "مَرَرْتُ بِالبَيْتِ {word}.",
            requiredForm: "النَّظِيفِ",
            role: "نعت مجرور",
            explanation: "«النظيف» وصفٌ لـ«البيتِ» المجرور؛ فتحتاج الجملة «النَّظِيفِ».",
          },
          {
            id: "nominative",
            sentence: "أَعْجَبَنِي البَيْتُ {word}.",
            requiredForm: "النَّظِيفُ",
            role: "نعت مرفوع",
            explanation: "«النظيف» وصفٌ لـ«البيتُ» المرفوع؛ والنعت يتبع منعوته في الرفع.",
          },
        ],
      },
      {
        id: "returns-present",
        topic: "الفعل المضارع",
        skill: "الرفع والنصب والجزم",
        word: "يَعُودُ",
        correctChoiceId: "indicative",
        hint: "ابحث عن الفعل الذي لم يسبقه «لن» أو «لم».",
        choices: [
          {
            id: "indicative",
            sentence: "المُسَافِرُ {word} مَسَاءً.",
            requiredForm: "يَعُودُ",
            role: "فعل مضارع مرفوع",
            explanation: "لم يسبق الفعل ناصب ولا جازم؛ فهو مرفوع بالضمة.",
          },
          {
            id: "subjunctive",
            sentence: "لَنْ {word} المُسَافِرُ اليَوْمَ.",
            requiredForm: "يَعُودَ",
            role: "فعل مضارع منصوب",
            explanation: "سبق الفعلَ «لن»؛ فتحتاج الجملة «يَعُودَ» بالفتحة.",
          },
          {
            id: "jussive",
            sentence: "لَمْ {word} المُسَافِرُ أَمْسِ.",
            requiredForm: "يَعُدْ",
            role: "فعل مضارع مجزوم",
            explanation: "سبق الفعلَ «لم»؛ فتحتاج الجملة «يَعُدْ» بالسكون بعد حذف الواو.",
          },
        ],
      },
      {
        id: "call-imperative",
        topic: "فعل الأمر",
        skill: "البناء على حذف حرف العلة",
        word: "اُدْعُ",
        correctChoiceId: "imperative",
        hint: "ابحث عن طلب مباشر موجّه إلى شخص واحد.",
        choices: [
          {
            id: "present",
            sentence: "الأَبُ {word} الضُّيُوفَ إِلَى العَشَاءِ.",
            requiredForm: "يَدْعُو",
            role: "فعل مضارع مرفوع",
            explanation: "الجملة تخبر عما يفعله الأب؛ فتحتاج المضارع «يَدْعُو».",
          },
          {
            id: "imperative",
            sentence: "يَا أَخِي، {word} الضُّيُوفَ إِلَى العَشَاءِ.",
            requiredForm: "اُدْعُ",
            role: "فعل أمر مبني على حذف حرف العلة",
            explanation: "الجملة طلب مباشر؛ وصيغة الأمر من «يدعو» هي «اُدْعُ» بحذف الواو.",
          },
          {
            id: "jussive",
            sentence: "لَمْ {word} الأَبُ الضُّيُوفَ أَمْسِ.",
            requiredForm: "يَدْعُ",
            role: "فعل مضارع مجزوم بحذف حرف العلة",
            explanation: "سبق الفعلَ «لم»؛ فتحتاج المضارع المجزوم «يَدْعُ»، لا فعل الأمر.",
          },
        ],
      },
      {
        id: "your-home-five-nouns",
        topic: "الأسماء الخمسة",
        skill: "النصب بالألف",
        word: "ذَا خُلُقٍ",
        correctChoiceId: "object",
        hint: "ابحث عن الجملة التي وقع فيها التكريم على صاحب الخلق.",
        choices: [
          {
            id: "subject",
            sentence: "حَضَرَ {word} إِلَى المَجْلِسِ.",
            requiredForm: "ذُو خُلُقٍ",
            role: "فاعل مرفوع",
            explanation: "صاحب الخلق هو الذي حضر؛ وتحتاج الجملة «ذُو خُلُقٍ» لأن «ذو» مرفوعة بالواو.",
          },
          {
            id: "object",
            sentence: "كَرَّمْنَا {word}.",
            requiredForm: "ذَا خُلُقٍ",
            role: "مفعول به منصوب",
            explanation: "وقع التكريم على صاحب الخلق؛ و«ذا» من الأسماء الخمسة المنصوبة بالألف.",
          },
          {
            id: "genitive",
            sentence: "سَلَّمْنَا عَلَى {word}.",
            requiredForm: "ذِي خُلُقٍ",
            role: "اسم مجرور",
            explanation: "سبقت الكلمة بحرف الجر «على»؛ فتحتاج الجملة «ذِي خُلُقٍ» بالياء.",
          },
        ],
      },
    ],
  };
