import type { PlaceGameCycle } from "./model";

export const CourtMediaCycle: PlaceGameCycle = {
    id: "court-media",
    title: "غرفة الأخبار",
    theme: "المحكمة والإعلام ودقة الحكم",
    challenges: [
      {
        id: "judge-accusative-manqous",
        topic: "الاسم المنقوص",
        skill: "ظهور الفتحة في النصب",
        word: "القَاضِيَ",
        correctChoiceId: "object",
        hint: "في الاسم المنقوص تظهر الفتحة عند النصب، وتُقدَّر الحركة في الرفع والجر.",
        choices: [
          {
            id: "subject",
            sentence: "حَكَمَ {word} بِالعَدْلِ.",
            requiredForm: "القَاضِي",
            role: "فاعل مرفوع بضمة مقدرة",
            explanation: "القاضي هو الذي حكم؛ فهو فاعل مرفوع بضمة مقدرة على الياء، فلا تظهر الفتحة: «القَاضِي».",
          },
          {
            id: "object",
            sentence: "قَابَلَ الصَّحَفِيُّ {word} بَعْدَ الجَلْسَةِ.",
            requiredForm: "القَاضِيَ",
            role: "مفعول به منصوب",
            explanation: "وقع فعل المقابلة على القاضي؛ فهو مفعول به منصوب، وتظهر الفتحة على ياء الاسم المنقوص.",
          },
          {
            id: "genitive",
            sentence: "سَلَّمَ الصَّحَفِيُّ عَلَى {word}.",
            requiredForm: "القَاضِي",
            role: "اسم مجرور بكسرة مقدرة",
            explanation: "سبقت الكلمة بحرف الجر «على»؛ فهي مجرورة بكسرة مقدرة، وصورتها «القَاضِي» بلا فتحة ظاهرة.",
          },
        ],
      },
      {
        id: "journalist-subject",
        topic: "الفاعل",
        skill: "الرفع بالضمة",
        word: "الصَّحَفِيُّ",
        correctChoiceId: "subject",
        hint: "ابحث عن الجملة التي كتب فيها الصحفي الخبر بنفسه.",
        choices: [
          {
            id: "subject",
            sentence: "كَتَبَ {word} الخَبَرَ.",
            requiredForm: "الصَّحَفِيُّ",
            role: "فاعل مرفوع",
            explanation: "الصحفي هو الذي كتب؛ فهو فاعل مرفوع بالضمة.",
          },
          {
            id: "object",
            sentence: "اِسْتَضَافَ المُذِيعُ {word}.",
            requiredForm: "الصَّحَفِيَّ",
            role: "مفعول به منصوب",
            explanation: "وقع فعل الاستضافة على الصحفي؛ فتحتاج الجملة «الصَّحَفِيَّ» بالفتحة.",
          },
          {
            id: "genitive",
            sentence: "تَحَدَّثَ المُذِيعُ مَعَ {word}.",
            requiredForm: "الصَّحَفِيِّ",
            role: "مضاف إليه مجرور",
            explanation: "جاءت الكلمة بعد «مع» المضافة؛ فتحتاج الجملة «الصَّحَفِيِّ» بالكسرة.",
          },
        ],
      },
      {
        id: "report-accurate",
        topic: "كان وأخواتها",
        skill: "خبر كان منصوب",
        word: "دَقِيقًا",
        correctChoiceId: "kana",
        hint: "ابحث عن الجملة التي دخلت فيها «كان» على الخبر.",
        choices: [
          {
            id: "nominal",
            sentence: "التَّقْرِيرُ {word}.",
            requiredForm: "دَقِيقٌ",
            role: "خبر مرفوع",
            explanation: "الجملة الاسمية بلا ناسخ تحتاج خبرًا مرفوعًا: «دَقِيقٌ».",
          },
          {
            id: "kana",
            sentence: "كَانَ التَّقْرِيرُ {word}.",
            requiredForm: "دَقِيقًا",
            role: "خبر كان منصوب",
            explanation: "دخلت «كان» فنصبت الخبر؛ لذلك جاءت «دَقِيقًا» بالفتحة.",
          },
          {
            id: "inna",
            sentence: "إِنَّ التَّقْرِيرَ {word}.",
            requiredForm: "دَقِيقٌ",
            role: "خبر إن مرفوع",
            explanation: "خبر «إنَّ» مرفوع؛ لذلك تحتاج الجملة «دَقِيقٌ» بالضمة.",
          },
        ],
      },
      {
        id: "truth-starter",
        topic: "المبتدأ",
        skill: "الرفع بالضمة",
        word: "الحَقُّ",
        correctChoiceId: "starter",
        hint: "ابحث عن جملة بدأت بالحق وتحدثت عنه.",
        choices: [
          {
            id: "object",
            sentence: "عَرَفَ القَاضِي {word}.",
            requiredForm: "الحَقَّ",
            role: "مفعول به منصوب",
            explanation: "وقع فعل المعرفة على الحق؛ فتحتاج الجملة «الحَقَّ» بالفتحة.",
          },
          {
            id: "genitive",
            sentence: "دَافَعَ المُحَامِي عَنِ {word}.",
            requiredForm: "الحَقِّ",
            role: "اسم مجرور",
            explanation: "سبقت الكلمة بحرف الجر «عن»؛ فتحتاج الجملة «الحَقِّ» بالكسرة.",
          },
          {
            id: "starter",
            sentence: "{word} وَاضِحٌ.",
            requiredForm: "الحَقُّ",
            role: "مبتدأ مرفوع",
            explanation: "بدأت الجملة بالحق وتحدثت عنه؛ فهو مبتدأ مرفوع بالضمة.",
          },
        ],
      },
      {
        id: "journalists-present-five-verbs",
        topic: "الأفعال الخمسة",
        skill: "الرفع بثبوت النون",
        word: "يَنْشُرُونَ",
        correctChoiceId: "indicative",
        hint: "ابحث عن الفعل الذي لم يسبقه «لن» أو «لم».",
        choices: [
          {
            id: "subjunctive",
            sentence: "الصَّحَفِيُّونَ لَنْ {word} الخَبَرَ قَبْلَ التَّحَقُّقِ.",
            requiredForm: "يَنْشُرُوا",
            role: "فعل مضارع منصوب بحذف النون",
            explanation: "سبق الفعلَ «لن»؛ وعلامة نصب الأفعال الخمسة حذف النون، فتحتاج الجملة «يَنْشُرُوا».",
          },
          {
            id: "indicative",
            sentence: "الصَّحَفِيُّونَ {word} الخَبَرَ بَعْدَ التَّحَقُّقِ.",
            requiredForm: "يَنْشُرُونَ",
            role: "فعل مضارع مرفوع بثبوت النون",
            explanation: "لم يسبق الفعل ناصب ولا جازم؛ فهو من الأفعال الخمسة المرفوعة بثبوت النون.",
          },
          {
            id: "jussive",
            sentence: "الصَّحَفِيُّونَ لَمْ {word} الخَبَرَ المُضَلِّلَ.",
            requiredForm: "يَنْشُرُوا",
            role: "فعل مضارع مجزوم بحذف النون",
            explanation: "سبق الفعلَ «لم»؛ وعلامة جزم الأفعال الخمسة حذف النون، فتحتاج الجملة «يَنْشُرُوا».",
          },
        ],
      },
      {
        id: "publish-imperative",
        topic: "فعل الأمر",
        skill: "البناء على حذف النون",
        word: "اُنْشُرُوا",
        correctChoiceId: "imperative",
        hint: "ابحث عن نداء يتبعه طلب نشر مباشر.",
        choices: [
          {
            id: "past",
            sentence: "الصَّحَفِيُّونَ {word} الحَقِيقَةَ أَمْسِ.",
            requiredForm: "نَشَرُوا",
            role: "فعل ماضٍ",
            explanation: "الجملة تتحدث عن حدث انتهى أمس؛ فتحتاج الماضي «نَشَرُوا».",
          },
          {
            id: "imperative",
            sentence: "يَا صَحَفِيُّونَ، {word} الحَقِيقَةَ.",
            requiredForm: "اُنْشُرُوا",
            role: "فعل أمر مبني على حذف النون",
            explanation: "الجملة طلب مباشر بعد النداء؛ لذلك تلائمها صيغة الأمر «اُنْشُرُوا».",
          },
          {
            id: "present",
            sentence: "الصَّحَفِيُّونَ {word} الحَقِيقَةَ كُلَّ يَوْمٍ.",
            requiredForm: "يَنْشُرُونَ",
            role: "فعل مضارع مرفوع",
            explanation: "الجملة تصف عملًا متكررًا؛ فتحتاج المضارع «يَنْشُرُونَ».",
          },
        ],
      },
      {
        id: "lawyer-manqous-object",
        topic: "الاسم المنقوص",
        skill: "الفتحة الظاهرة في النصب",
        word: "المُحَامِيَ",
        correctChoiceId: "object",
        hint: "فتحة الاسم المنقوص تظهر عندما يكون منصوبًا.",
        choices: [
          {
            id: "subject",
            sentence: "دَافَعَ {word} عَنِ المُتَّهَمِ.",
            requiredForm: "المُحَامِي",
            role: "فاعل مرفوع بضمة مقدرة",
            explanation: "المحامي هو الذي دافع؛ فهو فاعل مرفوع بضمة مقدرة، وصورته «المُحَامِي».",
          },
          {
            id: "object",
            sentence: "شَكَرَ المُتَّهَمُ {word}.",
            requiredForm: "المُحَامِيَ",
            role: "مفعول به منصوب",
            explanation: "وقع فعل الشكر على المحامي؛ فهو مفعول به منصوب، وتظهر الفتحة على الياء.",
          },
          {
            id: "genitive",
            sentence: "اِسْتَمَعَ القَاضِي إِلَى {word}.",
            requiredForm: "المُحَامِي",
            role: "اسم مجرور بكسرة مقدرة",
            explanation: "جاء الاسم بعد «إلى»؛ فهو مجرور بكسرة مقدرة، وصورته «المُحَامِي».",
          },
        ],
      },
    ],
  };
