import type { PlaceGameCycle } from "./model";

export const SportsHealthCycle: PlaceGameCycle = {
    id: "sports-health",
    title: "ملعب الحركات",
    theme: "الرياضة والصحة والأفعال المعتلة",
    challenges: [
      {
        id: "player-subject",
        topic: "الفاعل",
        skill: "الرفع بالضمة",
        word: "اللَّاعِبُ",
        correctChoiceId: "subject",
        hint: "ابحث عن الجملة التي قام فيها اللاعب بالتدرب.",
        choices: [
          {
            id: "object",
            sentence: "شَجَّعَ الجُمْهُورُ {word}.",
            requiredForm: "اللَّاعِبَ",
            role: "مفعول به منصوب",
            explanation: "وقع التشجيع على اللاعب؛ فتحتاج الجملة «اللَّاعِبَ» بالفتحة.",
          },
          {
            id: "subject",
            sentence: "تَدَرَّبَ {word} صَبَاحًا.",
            requiredForm: "اللَّاعِبُ",
            role: "فاعل مرفوع",
            explanation: "اللاعب هو الذي تدرب؛ فهو فاعل مرفوع بالضمة.",
          },
          {
            id: "genitive",
            sentence: "تَحَدَّثَ المُدَرِّبُ مَعَ {word}.",
            requiredForm: "اللَّاعِبِ",
            role: "مضاف إليه مجرور",
            explanation: "جاء الاسم بعد «مع» المضافة؛ فتحتاج الجملة «اللَّاعِبِ» بالكسرة.",
          },
        ],
      },
      {
        id: "player-object",
        topic: "المفعول به",
        skill: "النصب بالفتحة",
        word: "اللَّاعِبَ",
        correctChoiceId: "object",
        hint: "ابحث عن الجملة التي وقع فيها الاختيار على اللاعب.",
        choices: [
          {
            id: "subject",
            sentence: "فَازَ {word} بِالسِّبَاقِ.",
            requiredForm: "اللَّاعِبُ",
            role: "فاعل مرفوع",
            explanation: "اللاعب هو الذي فاز؛ فتحتاج الجملة «اللَّاعِبُ» بالضمة.",
          },
          {
            id: "genitive",
            sentence: "سَأَلْتُ عَنِ {word}.",
            requiredForm: "اللَّاعِبِ",
            role: "اسم مجرور",
            explanation: "سبقت الكلمة بحرف الجر «عن»؛ فتحتاج الجملة «اللَّاعِبِ» بالكسرة.",
          },
          {
            id: "object",
            sentence: "اِخْتَارَ المُدَرِّبُ {word} لِلْمُبَارَاةِ.",
            requiredForm: "اللَّاعِبَ",
            role: "مفعول به منصوب",
            explanation: "وقع فعل الاختيار على اللاعب؛ فهو مفعول به منصوب بالفتحة.",
          },
        ],
      },
      {
        id: "fast-adjective",
        topic: "النعت",
        skill: "النعت يتبع المنعوت",
        word: "السَّرِيعُ",
        correctChoiceId: "nominative",
        hint: "راقب حركة كلمة «العدّاء» قبل الصفة.",
        choices: [
          {
            id: "nominative",
            sentence: "فَازَ العَدَّاءُ {word}.",
            requiredForm: "السَّرِيعُ",
            role: "نعت مرفوع",
            explanation: "«السريع» وصفٌ لـ«العدّاءُ» المرفوع؛ والنعت يتبع منعوته في الرفع.",
          },
          {
            id: "accusative",
            sentence: "شَجَّعْتُ العَدَّاءَ {word}.",
            requiredForm: "السَّرِيعَ",
            role: "نعت منصوب",
            explanation: "«السريع» وصفٌ لـ«العدّاءَ» المنصوب؛ فتحتاج الجملة «السَّرِيعَ» بالفتحة.",
          },
          {
            id: "genitive",
            sentence: "تَحَدَّثْتُ عَنِ العَدَّاءِ {word}.",
            requiredForm: "السَّرِيعِ",
            role: "نعت مجرور",
            explanation: "«السريع» وصفٌ لـ«العدّاءِ» المجرور؛ فتحتاج الجملة «السَّرِيعِ» بالكسرة.",
          },
        ],
      },
      {
        id: "child-became-active",
        topic: "كان وأخواتها",
        skill: "خبر أصبح منصوب",
        word: "نَشِيطًا",
        correctChoiceId: "became",
        hint: "ابحث عن «أصبح»؛ فهي تنصب الخبر.",
        choices: [
          {
            id: "nominal",
            sentence: "الطِّفْلُ {word}.",
            requiredForm: "نَشِيطٌ",
            role: "خبر مرفوع",
            explanation: "هذه جملة اسمية بلا ناسخ؛ فتحتاج خبرًا مرفوعًا: «نَشِيطٌ».",
          },
          {
            id: "became",
            sentence: "أَصْبَحَ الطِّفْلُ {word}.",
            requiredForm: "نَشِيطًا",
            role: "خبر أصبح منصوب",
            explanation: "«أصبح» من أخوات كان وتنصب الخبر؛ لذلك جاءت «نَشِيطًا».",
          },
          {
            id: "inna",
            sentence: "إِنَّ الطِّفْلَ {word}.",
            requiredForm: "نَشِيطٌ",
            role: "خبر إن مرفوع",
            explanation: "خبر «إنَّ» مرفوع؛ فتحتاج الجملة «نَشِيطٌ» بالضمة.",
          },
        ],
      },
      {
        id: "runs-subjunctive",
        topic: "الفعل المضارع المعتل",
        skill: "النصب بالفتحة الظاهرة",
        word: "يَجْرِيَ",
        correctChoiceId: "subjunctive",
        hint: "ابحث عن «لن»؛ فهي تنصب الفعل المضارع.",
        choices: [
          {
            id: "indicative",
            sentence: "اللَّاعِبُ {word} كُلَّ صَبَاحٍ.",
            requiredForm: "يَجْرِي",
            role: "فعل مضارع مرفوع بضمة مقدرة",
            explanation: "لم يسبق الفعل ناصب ولا جازم؛ فهو مرفوع بضمة مقدرة، وصورته «يَجْرِي» بلا فتحة.",
          },
          {
            id: "subjunctive",
            sentence: "لَنْ {word} اللَّاعِبُ وَهُوَ مُصَابٌ.",
            requiredForm: "يَجْرِيَ",
            role: "فعل مضارع منصوب",
            explanation: "سبق الفعلَ «لن»؛ فهو منصوب، وتظهر الفتحة على الياء: «يَجْرِيَ».",
          },
          {
            id: "jussive",
            sentence: "لَمْ {word} اللَّاعِبُ أَمْسِ.",
            requiredForm: "يَجْرِ",
            role: "فعل مضارع مجزوم بحذف حرف العلة",
            explanation: "سبق الفعلَ «لم»؛ فهو مجزوم بحذف حرف العلة، فتحتاج الجملة «يَجْرِ».",
          },
        ],
      },
      {
        id: "throw-imperative",
        topic: "فعل الأمر",
        skill: "البناء على حذف حرف العلة",
        word: "اِرْمِ",
        correctChoiceId: "imperative",
        hint: "ابحث عن نداء يتبعه طلب رمي الكرة.",
        choices: [
          {
            id: "present",
            sentence: "اللَّاعِبُ {word} الكُرَةَ نَحْوَ الهَدَفِ.",
            requiredForm: "يَرْمِي",
            role: "فعل مضارع مرفوع",
            explanation: "الجملة تخبر عما يفعله اللاعب؛ فتحتاج المضارع «يَرْمِي».",
          },
          {
            id: "imperative",
            sentence: "يَا لَاعِبُ، {word} الكُرَةَ نَحْوَ الهَدَفِ.",
            requiredForm: "اِرْمِ",
            role: "فعل أمر مبني على حذف حرف العلة",
            explanation: "الجملة طلب مباشر؛ وصيغة الأمر من «يرمي» هي «اِرْمِ» بحذف الياء.",
          },
          {
            id: "jussive",
            sentence: "لَمْ {word} اللَّاعِبُ الكُرَةَ بَعِيدًا.",
            requiredForm: "يَرْمِ",
            role: "فعل مضارع مجزوم بحذف حرف العلة",
            explanation: "سبق الفعلَ «لم»؛ فتحتاج الجملة المضارع المجزوم «يَرْمِ»، لا فعل الأمر.",
          },
        ],
      },
      {
        id: "his-team",
        topic: "الضمير المتصل",
        skill: "الموقع يغيّر حركة الاسم",
        word: "فَرِيقُهُ",
        correctChoiceId: "starter",
        hint: "حدّد هل الفريق هو موضوع الحديث، أم وقع عليه الفعل، أم سبق بحرف جر.",
        choices: [
          {
            id: "object",
            sentence: "شَجَّعَ الجُمْهُورُ {word}.",
            requiredForm: "فَرِيقَهُ",
            role: "مفعول به منصوب",
            explanation: "وقع فعل التشجيع على الفريق؛ فتحتاج الجملة «فَرِيقَهُ» بالفتحة قبل الضمير.",
          },
          {
            id: "genitive",
            sentence: "تَحَدَّثَ المُدَرِّبُ عَنْ {word}.",
            requiredForm: "فَرِيقِهِ",
            role: "اسم مجرور",
            explanation: "سبق الاسم بحرف الجر «عن»؛ فتحتاج الجملة «فَرِيقِهِ» بالكسرة قبل الضمير.",
          },
          {
            id: "starter",
            sentence: "{word} مُتَمَاسِكٌ.",
            requiredForm: "فَرِيقُهُ",
            role: "مبتدأ مرفوع",
            explanation: "بدأت الجملة بالفريق وتحدثت عنه؛ فهو مبتدأ مرفوع، ولذلك جاءت الضمة قبل الضمير.",
          },
        ],
      },
    ],
  };
