import type { PlaceGameCycle } from "./model";

export const WorkProjectsCycle: PlaceGameCycle = {
    id: "work-projects",
    title: "مهمّة الفريق",
    theme: "العمل والمشروعات والعلامات الفرعية",
    challenges: [
      {
        id: "engineers-dual",
        topic: "المثنى",
        skill: "الرفع بالألف",
        word: "المُهَنْدِسَانِ",
        correctChoiceId: "subject",
        hint: "ابحث عن الجملة التي قام فيها المهندسان بالفعل.",
        choices: [
          {
            id: "subject",
            sentence: "رَاجَعَ {word} المُخَطَّطَ.",
            requiredForm: "المُهَنْدِسَانِ",
            role: "فاعل مرفوع",
            explanation: "المهندسان قاما بالمراجعة؛ فهما فاعل مرفوع، وعلامة رفع المثنى الألف.",
          },
          {
            id: "object",
            sentence: "اِسْتَقْبَلَ المُدِيرُ {word}.",
            requiredForm: "المُهَنْدِسَيْنِ",
            role: "مفعول به منصوب",
            explanation: "وقع فعل الاستقبال على المهندسَيْن؛ فتحتاج الجملة صيغة المثنى المنصوبة بالياء: «المُهَنْدِسَيْنِ».",
          },
          {
            id: "genitive",
            sentence: "تَحَدَّثْتُ مَعَ {word}.",
            requiredForm: "المُهَنْدِسَيْنِ",
            role: "مضاف إليه مجرور",
            explanation: "جاء المثنى بعد «مع» المضافة؛ فتحتاج الجملة صيغة الجر بالياء: «المُهَنْدِسَيْنِ».",
          },
        ],
      },
      {
        id: "diligent-workers",
        topic: "جمع المذكر السالم",
        skill: "الرفع بالواو",
        word: "المُجْتَهِدُونَ",
        correctChoiceId: "subject",
        hint: "ابحث عن الجملة التي يكون فيها المجتهدون هم الفائزين بالفعل.",
        choices: [
          {
            id: "object",
            sentence: "كَرَّمْنَا {word} فِي الحَفْلِ.",
            requiredForm: "المُجْتَهِدِينَ",
            role: "مفعول به منصوب",
            explanation: "وقع التكريم على المجتهدين؛ وعلامة نصب جمع المذكر السالم الياء: «المُجْتَهِدِينَ».",
          },
          {
            id: "genitive",
            sentence: "تَحَدَّثْنَا عَنِ {word}.",
            requiredForm: "المُجْتَهِدِينَ",
            role: "اسم مجرور",
            explanation: "سبقت الكلمة بحرف الجر «عن»؛ وعلامة جر جمع المذكر السالم الياء: «المُجْتَهِدِينَ».",
          },
          {
            id: "subject",
            sentence: "فَازَ {word} بِالجَائِزَةِ.",
            requiredForm: "المُجْتَهِدُونَ",
            role: "فاعل مرفوع",
            explanation: "المجتهدون هم الذين فازوا؛ وعلامة رفع جمع المذكر السالم الواو.",
          },
        ],
      },
      {
        id: "manager-kana-predicate",
        topic: "كان وأخواتها",
        skill: "خبر كان منصوب",
        word: "حَاضِرًا",
        correctChoiceId: "kana",
        hint: "ابحث عن ناسخ يغيّر حكم الخبر إلى النصب.",
        choices: [
          {
            id: "nominal",
            sentence: "المُدِيرُ {word}.",
            requiredForm: "حَاضِرٌ",
            role: "خبر مرفوع",
            explanation: "هذه جملة اسمية بلا ناسخ؛ فالخبر مرفوع، وتحتاج الجملة «حَاضِرٌ» بالضمة.",
          },
          {
            id: "inna",
            sentence: "إِنَّ المُدِيرَ {word}.",
            requiredForm: "حَاضِرٌ",
            role: "خبر إن مرفوع",
            explanation: "«إنَّ» تنصب اسمها وترفع خبرها؛ لذلك تحتاج الجملة «حَاضِرٌ» بالضمة.",
          },
          {
            id: "kana",
            sentence: "كَانَ المُدِيرُ {word}.",
            requiredForm: "حَاضِرًا",
            role: "خبر كان منصوب",
            explanation: "دخلت «كان» فرفعت الاسم ونصبت الخبر؛ لذلك جاءت «حَاضِرًا» بالفتحة.",
          },
        ],
      },
      {
        id: "manager-inna-name",
        topic: "إن وأخواتها",
        skill: "اسم إن منصوب",
        word: "المُدِيرَ",
        correctChoiceId: "inna",
        hint: "ابحث عن «إنَّ» ثم حدّد الاسم الذي دخلت عليه.",
        choices: [
          {
            id: "kana",
            sentence: "كَانَ {word} مُنَظَّمًا.",
            requiredForm: "المُدِيرُ",
            role: "اسم كان مرفوع",
            explanation: "اسم «كان» مرفوع؛ لذلك تحتاج الجملة «المُدِيرُ» بالضمة.",
          },
          {
            id: "inna",
            sentence: "إِنَّ {word} مُنَظَّمٌ.",
            requiredForm: "المُدِيرَ",
            role: "اسم إن منصوب",
            explanation: "«إنَّ» تنصب اسمها؛ لذلك جاءت «المُدِيرَ» بالفتحة.",
          },
          {
            id: "genitive",
            sentence: "تَحَدَّثْتُ مَعَ {word}.",
            requiredForm: "المُدِيرِ",
            role: "مضاف إليه مجرور",
            explanation: "جاء الاسم بعد «مع» المضافة؛ لذلك تحتاج الجملة «المُدِيرِ» بالكسرة.",
          },
        ],
      },
      {
        id: "employees-past",
        topic: "الفعل الماضي",
        skill: "تمييز الماضي من المضارع والأمر",
        word: "كَتَبُوا",
        correctChoiceId: "past",
        hint: "ابحث عن جملة تتحدث عن عمل انتهى أمس.",
        choices: [
          {
            id: "present",
            sentence: "المُوَظَّفُونَ {word} التَّقْرِيرَ اليَوْمَ.",
            requiredForm: "يَكْتُبُونَ",
            role: "فعل مضارع مرفوع",
            explanation: "الجملة تتحدث عن عمل يحدث اليوم؛ فتحتاج فعلًا مضارعًا: «يَكْتُبُونَ».",
          },
          {
            id: "past",
            sentence: "المُوَظَّفُونَ {word} التَّقْرِيرَ أَمْسِ.",
            requiredForm: "كَتَبُوا",
            role: "فعل ماضٍ مبني",
            explanation: "الحدث وقع وانتهى أمس؛ لذلك تلائمه صيغة الماضي «كَتَبُوا».",
          },
          {
            id: "imperative",
            sentence: "يَا مُوَظَّفُونَ، {word} التَّقْرِيرَ الآنَ.",
            requiredForm: "اُكْتُبُوا",
            role: "فعل أمر",
            explanation: "الجملة تطلب من الموظفين الكتابة الآن؛ فتحتاج فعل الأمر «اُكْتُبُوا».",
          },
        ],
      },
      {
        id: "employees-imperative",
        topic: "فعل الأمر",
        skill: "الأمر المتصل بواو الجماعة",
        word: "اُكْتُبُوا",
        correctChoiceId: "imperative",
        hint: "ابحث عن نداء يتبعه طلب مباشر.",
        choices: [
          {
            id: "past",
            sentence: "المُوَظَّفُونَ {word} المُلَاحَظَاتِ أَمْسِ.",
            requiredForm: "كَتَبُوا",
            role: "فعل ماضٍ",
            explanation: "وجود «أمس» يدل على حدث منتهٍ؛ فتحتاج الجملة «كَتَبُوا» لا فعل الأمر.",
          },
          {
            id: "present",
            sentence: "المُوَظَّفُونَ {word} المُلَاحَظَاتِ كُلَّ يَوْمٍ.",
            requiredForm: "يَكْتُبُونَ",
            role: "فعل مضارع مرفوع",
            explanation: "الجملة تصف عادة متكررة؛ فتحتاج المضارع «يَكْتُبُونَ».",
          },
          {
            id: "imperative",
            sentence: "يَا مُوَظَّفُونَ، {word} المُلَاحَظَاتِ بِدِقَّةٍ.",
            requiredForm: "اُكْتُبُوا",
            role: "فعل أمر مبني على حذف النون",
            explanation: "الجملة طلب مباشر بعد النداء؛ لذلك تلائمها صيغة الأمر «اُكْتُبُوا».",
          },
        ],
      },
      {
        id: "teacher-conjunction",
        topic: "العطف",
        skill: "المعطوف يتبع المعطوف عليه",
        word: "المُعَلِّمُ",
        correctChoiceId: "nominative",
        hint: "راقب حركة الاسم الذي يسبق حرف العطف «الواو».",
        choices: [
          {
            id: "nominative",
            sentence: "حَضَرَ المُدِيرُ وَ{word}.",
            requiredForm: "المُعَلِّمُ",
            role: "معطوف مرفوع",
            explanation: "«المعلّم» معطوف على «المديرُ» المرفوع؛ والمعطوف يتبع المعطوف عليه في الرفع.",
          },
          {
            id: "accusative",
            sentence: "قَابَلْتُ المُدِيرَ وَ{word}.",
            requiredForm: "المُعَلِّمَ",
            role: "معطوف منصوب",
            explanation: "«المعلّم» معطوف على «المديرَ» المنصوب؛ فتحتاج الجملة «المُعَلِّمَ» بالفتحة.",
          },
          {
            id: "genitive",
            sentence: "سَلَّمْتُ عَلَى المُدِيرِ وَ{word}.",
            requiredForm: "المُعَلِّمِ",
            role: "معطوف مجرور",
            explanation: "«المعلّم» معطوف على «المديرِ» المجرور؛ فتحتاج الجملة «المُعَلِّمِ» بالكسرة.",
          },
        ],
      },
    ],
  };
