import type { PlaceGameCycle } from "./model";

export const ResearchNatureCycle: PlaceGameCycle = {
    id: "research-nature",
    title: "مختبر المعرفة",
    theme: "البحث والطبيعة والتعلّم",
    challenges: [
      {
        id: "researcher-subject",
        topic: "الفاعل",
        skill: "الرفع بالضمة",
        word: "البَاحِثَةُ",
        correctChoiceId: "subject",
        hint: "ابحث عن الجملة التي قامت فيها الباحثة بالاكتشاف.",
        choices: [
          {
            id: "subject",
            sentence: "اِكْتَشَفَتِ {word} نَتِيجَةً مُهِمَّةً.",
            requiredForm: "البَاحِثَةُ",
            role: "فاعل مرفوع",
            explanation: "الباحثة هي التي اكتشفت؛ فهي فاعل مرفوع بالضمة.",
          },
          {
            id: "object",
            sentence: "كَرَّمَتِ الجَامِعَةُ {word}.",
            requiredForm: "البَاحِثَةَ",
            role: "مفعول به منصوب",
            explanation: "وقع التكريم على الباحثة؛ فتحتاج الجملة «البَاحِثَةَ» بالفتحة.",
          },
          {
            id: "genitive",
            sentence: "اِسْتَمَعَ الطُّلَّابُ إِلَى {word}.",
            requiredForm: "البَاحِثَةِ",
            role: "اسم مجرور",
            explanation: "جاءت الكلمة بعد حرف الجر «إلى»؛ فتحتاج الجملة «البَاحِثَةِ» بالكسرة.",
          },
        ],
      },
      {
        id: "result-object",
        topic: "المفعول به",
        skill: "النصب بالفتحة",
        word: "النَّتِيجَةَ",
        correctChoiceId: "object",
        hint: "ابحث عن الجملة التي وقع فيها التسجيل على النتيجة.",
        choices: [
          {
            id: "starter",
            sentence: "{word} وَاضِحَةٌ.",
            requiredForm: "النَّتِيجَةُ",
            role: "مبتدأ مرفوع",
            explanation: "بدأت الجملة بالنتيجة وتحدثت عنها؛ فتحتاج «النَّتِيجَةُ» بالضمة.",
          },
          {
            id: "object",
            sentence: "سَجَّلَتِ البَاحِثَةُ {word}.",
            requiredForm: "النَّتِيجَةَ",
            role: "مفعول به منصوب",
            explanation: "وقع فعل التسجيل على النتيجة؛ فهي مفعول به منصوب بالفتحة.",
          },
          {
            id: "genitive",
            sentence: "تَحَدَّثَ الفَرِيقُ عَنِ {word}.",
            requiredForm: "النَّتِيجَةِ",
            role: "اسم مجرور",
            explanation: "سبقت الكلمة بحرف الجر «عن»؛ فتحتاج الجملة «النَّتِيجَةِ» بالكسرة.",
          },
        ],
      },
      {
        id: "information-inna-predicate",
        topic: "إن وأخواتها",
        skill: "خبر إن مرفوع",
        word: "مُفِيدَةٌ",
        correctChoiceId: "inna",
        hint: "تذكّر: «إنَّ» تنصب الاسم وترفع الخبر.",
        choices: [
          {
            id: "kana",
            sentence: "كَانَتِ المَعْلُومَةُ {word}.",
            requiredForm: "مُفِيدَةً",
            role: "خبر كان منصوب",
            explanation: "خبر «كان» منصوب؛ فتحتاج الجملة «مُفِيدَةً» بالفتحة.",
          },
          {
            id: "inna",
            sentence: "إِنَّ المَعْلُومَةَ {word}.",
            requiredForm: "مُفِيدَةٌ",
            role: "خبر إن مرفوع",
            explanation: "«إنَّ» تنصب اسمها وترفع خبرها؛ لذلك جاءت «مُفِيدَةٌ» بالضمة.",
          },
          {
            id: "adjective",
            sentence: "قَرَأْتُ مَعْلُومَةً {word}.",
            requiredForm: "مُفِيدَةً",
            role: "نعت منصوب",
            explanation: "الكلمة تصف «معلومةً» المنصوبة؛ فتحتاج الجملة «مُفِيدَةً» بالفتحة.",
          },
        ],
      },
      {
        id: "new-discovery-adjective",
        topic: "النعت",
        skill: "اتباع المنعوت في الإعراب",
        word: "الجَدِيدُ",
        correctChoiceId: "nominative",
        hint: "راقب حركة كلمة «الاكتشاف» قبل النعت.",
        choices: [
          {
            id: "nominative",
            sentence: "ظَهَرَ الاِكْتِشَافُ {word}.",
            requiredForm: "الجَدِيدُ",
            role: "نعت مرفوع",
            explanation: "«الجديد» وصفٌ لـ«الاكتشافُ» المرفوع؛ والنعت يتبع منعوته في الرفع.",
          },
          {
            id: "accusative",
            sentence: "سَجَّلْنَا الاِكْتِشَافَ {word}.",
            requiredForm: "الجَدِيدَ",
            role: "نعت منصوب",
            explanation: "«الجديد» وصفٌ لـ«الاكتشافَ» المنصوب؛ فتحتاج الجملة «الجَدِيدَ» بالفتحة.",
          },
          {
            id: "genitive",
            sentence: "قَرَأْنَا عَنِ الاِكْتِشَافِ {word}.",
            requiredForm: "الجَدِيدِ",
            role: "نعت مجرور",
            explanation: "«الجديد» وصفٌ لـ«الاكتشافِ» المجرور؛ فتحتاج الجملة «الجَدِيدِ» بالكسرة.",
          },
        ],
      },
      {
        id: "discovers-present",
        topic: "الفعل المضارع",
        skill: "الرفع والنصب والجزم",
        word: "يَكْتَشِفُ",
        correctChoiceId: "indicative",
        hint: "ابحث عن المضارع الذي لم يسبقه عامل نصب أو جزم.",
        choices: [
          {
            id: "jussive",
            sentence: "لَمْ {word} الفَرِيقُ السَّبَبَ بَعْدُ.",
            requiredForm: "يَكْتَشِفْ",
            role: "فعل مضارع مجزوم",
            explanation: "سبق الفعلَ «لم»؛ فتحتاج الجملة «يَكْتَشِفْ» بالسكون.",
          },
          {
            id: "indicative",
            sentence: "الفَرِيقُ {word} حَقَائِقَ جَدِيدَةً.",
            requiredForm: "يَكْتَشِفُ",
            role: "فعل مضارع مرفوع",
            explanation: "لم يسبق الفعل ناصب ولا جازم؛ فهو مرفوع بالضمة.",
          },
          {
            id: "subjunctive",
            sentence: "لَنْ {word} الفَرِيقُ السَّبَبَ دُونَ تَجْرِبَةٍ.",
            requiredForm: "يَكْتَشِفَ",
            role: "فعل مضارع منصوب",
            explanation: "سبق الفعلَ «لن»؛ فتحتاج الجملة «يَكْتَشِفَ» بالفتحة.",
          },
        ],
      },
      {
        id: "two-information-subject",
        topic: "المثنى",
        skill: "الرفع بالألف",
        word: "مَعْلُومَتَانِ",
        correctChoiceId: "subject",
        hint: "ابحث عن الجملة التي ظهرت فيها المعلومتان بوصفهما فاعلًا.",
        choices: [
          {
            id: "subject",
            sentence: "ظَهَرَتْ {word} فِي التَّقْرِيرِ.",
            requiredForm: "مَعْلُومَتَانِ",
            role: "فاعل مرفوع",
            explanation: "المعلومتان هما اللتان ظهرتا؛ فهما فاعل مرفوع، وعلامة رفع المثنى الألف.",
          },
          {
            id: "object",
            sentence: "سَجَّلَ البَاحِثُ {word}.",
            requiredForm: "مَعْلُومَتَيْنِ",
            role: "مفعول به منصوب",
            explanation: "وقع التسجيل على معلومتين؛ فتحتاج الجملة صيغة المثنى المنصوبة بالياء: «مَعْلُومَتَيْنِ».",
          },
          {
            id: "genitive",
            sentence: "تَحَدَّثَ البَاحِثُ عَنْ {word}.",
            requiredForm: "مَعْلُومَتَيْنِ",
            role: "اسم مجرور",
            explanation: "سبقت الكلمة بحرف الجر «عن»؛ فتحتاج الجملة صيغة المثنى المجرورة بالياء.",
          },
        ],
      },
      {
        id: "you-write-five-verbs",
        topic: "الأفعال الخمسة",
        skill: "ثبوت النون في الرفع",
        word: "تَكْتُبِينَ",
        correctChoiceId: "indicative",
        hint: "ابحث عن الفعل المتصل بياء المخاطبة من غير ناصب ولا جازم.",
        choices: [
          {
            id: "subjunctive",
            sentence: "لَنْ {word} المُلَاحَظَاتِ قَبْلَ القِرَاءَةِ.",
            requiredForm: "تَكْتُبِي",
            role: "فعل مضارع منصوب بحذف النون",
            explanation: "سبق الفعلَ «لن»؛ وعلامة نصب الأفعال الخمسة حذف النون، فتحتاج الجملة «تَكْتُبِي».",
          },
          {
            id: "jussive",
            sentence: "لَمْ {word} المُلَاحَظَاتِ أَمْسِ.",
            requiredForm: "تَكْتُبِي",
            role: "فعل مضارع مجزوم بحذف النون",
            explanation: "سبق الفعلَ «لم»؛ وعلامة جزم الأفعال الخمسة حذف النون، فتحتاج الجملة «تَكْتُبِي».",
          },
          {
            id: "indicative",
            sentence: "أَنْتِ {word} المُلَاحَظَاتِ بِدِقَّةٍ.",
            requiredForm: "تَكْتُبِينَ",
            role: "فعل مضارع مرفوع بثبوت النون",
            explanation: "لم يسبق الفعل ناصب ولا جازم؛ فهو من الأفعال الخمسة المرفوعة بثبوت النون.",
          },
        ],
      },
    ],
  };
