import type { PlaceGameCycle } from "./model";

export const FamilyCommunityCycle: PlaceGameCycle = {
    id: "family-community",
    title: "محطّة الأسرة",
    theme: "الأسرة والضمائر والتوابع",
    challenges: [
      {
        id: "friend-predicate",
        topic: "الخبر",
        skill: "التنوين في الرفع والنصب والجر",
        word: "صَدِيقٌ",
        correctChoiceId: "predicate",
        hint: "ابحث عن الجملة التي تحتاج خبرًا مرفوعًا بعد اسم الإشارة.",
        choices: [
          {
            id: "predicate",
            sentence: "هٰذَا {word} وَفِيٌّ.",
            requiredForm: "صَدِيقٌ",
            role: "خبر مرفوع",
            explanation: "«صَدِيقٌ» أخبرت عن اسم الإشارة «هذا»؛ فهي خبر مرفوع بتنوين الضم.",
          },
          {
            id: "object",
            sentence: "زُرْتُ {word} وَفِيًّا.",
            requiredForm: "صَدِيقًا",
            role: "مفعول به منصوب",
            explanation: "وقع فعل الزيارة على الصديق؛ فتحتاج الجملة «صَدِيقًا» بتنوين الفتح.",
          },
          {
            id: "genitive",
            sentence: "مَرَرْتُ بِـ{word} وَفِيٍّ.",
            requiredForm: "صَدِيقٍ",
            role: "اسم مجرور",
            explanation: "سبقت الكلمة بالباء؛ فتحتاج الجملة «صَدِيقٍ» بتنوين الكسر.",
          },
        ],
      },
      {
        id: "mother-object",
        topic: "المفعول به",
        skill: "النصب بالفتحة",
        word: "الأُمَّ",
        correctChoiceId: "object",
        hint: "اسأل: مَن ساعدت البنت؟",
        choices: [
          {
            id: "subject",
            sentence: "حَضَرَتِ {word} إِلَى البَيْتِ.",
            requiredForm: "الأُمُّ",
            role: "فاعل مرفوع",
            explanation: "الأم هي التي حضرت؛ فتحتاج الجملة «الأُمُّ» بالضمة.",
          },
          {
            id: "object",
            sentence: "سَاعَدَتِ البِنْتُ {word}.",
            requiredForm: "الأُمَّ",
            role: "مفعول به منصوب",
            explanation: "وقع فعل المساعدة على الأم؛ فهي مفعول به منصوب بالفتحة.",
          },
          {
            id: "genitive",
            sentence: "اِسْتَمَعَتِ البِنْتُ إِلَى {word}.",
            requiredForm: "الأُمِّ",
            role: "اسم مجرور",
            explanation: "جاءت الكلمة بعد «إلى»؛ فتحتاج الجملة «الأُمِّ» بالكسرة.",
          },
        ],
      },
      {
        id: "brother-five-nouns",
        topic: "الأسماء الخمسة",
        skill: "الرفع بالواو",
        word: "أَخُوكَ",
        correctChoiceId: "subject",
        hint: "ابحث عن الجملة التي يكون فيها الأخ هو القادم من السفر.",
        choices: [
          {
            id: "subject",
            sentence: "وَصَلَ {word} مِنَ السَّفَرِ.",
            requiredForm: "أَخُوكَ",
            role: "فاعل مرفوع",
            explanation: "الأخ هو الذي وصل؛ فهو فاعل مرفوع، وعلامة رفع الأسماء الخمسة الواو.",
          },
          {
            id: "object",
            sentence: "رَأَيْتُ {word} فِي المَطَارِ.",
            requiredForm: "أَخَاكَ",
            role: "مفعول به منصوب",
            explanation: "وقع فعل الرؤية على الأخ؛ فتحتاج الجملة «أَخَاكَ» بالألف.",
          },
          {
            id: "genitive",
            sentence: "سَلَّمْتُ عَلَى {word}.",
            requiredForm: "أَخِيكَ",
            role: "اسم مجرور",
            explanation: "سبقت الكلمة بحرف الجر «على»؛ فتحتاج الجملة «أَخِيكَ» بالياء.",
          },
        ],
      },
      {
        id: "his-book",
        topic: "الضمير المتصل",
        skill: "تغيّر حركة الاسم قبل الضمير",
        word: "كِتَابُهُ",
        correctChoiceId: "starter",
        hint: "الضمير ثابت، لكن حركة آخر الاسم قبله تتغير بحسب الموقع.",
        choices: [
          {
            id: "starter",
            sentence: "{word} مُفِيدٌ.",
            requiredForm: "كِتَابُهُ",
            role: "مبتدأ مرفوع",
            explanation: "بدأت الجملة بالكتاب وتحدثت عنه؛ فهو مبتدأ مرفوع، ولذلك ضُمَّ آخر الاسم قبل الضمير.",
          },
          {
            id: "object",
            sentence: "قَرَأْتُ {word}.",
            requiredForm: "كِتَابَهُ",
            role: "مفعول به منصوب",
            explanation: "وقع فعل القراءة على الكتاب؛ فتحتاج الجملة «كِتَابَهُ» بالفتحة قبل الضمير.",
          },
          {
            id: "genitive",
            sentence: "اِسْتَفَدْتُ مِنْ {word}.",
            requiredForm: "كِتَابِهِ",
            role: "اسم مجرور",
            explanation: "جاء الاسم بعد «من»؛ فتحتاج الجملة «كِتَابِهِ» بالكسرة قبل الضمير.",
          },
        ],
      },
      {
        id: "same-father-emphasis",
        topic: "التوكيد",
        skill: "التوكيد يتبع المؤكَّد",
        word: "نَفْسُهُ",
        correctChoiceId: "nominative",
        hint: "راقب حركة الاسم الذي تؤكده كلمة «نفس».",
        choices: [
          {
            id: "nominative",
            sentence: "حَضَرَ الأَبُ {word}.",
            requiredForm: "نَفْسُهُ",
            role: "توكيد مرفوع",
            explanation: "«نفسه» تؤكد «الأبُ» المرفوع؛ والتوكيد يتبع المؤكَّد في الرفع.",
          },
          {
            id: "accusative",
            sentence: "قَابَلْتُ الأَبَ {word}.",
            requiredForm: "نَفْسَهُ",
            role: "توكيد منصوب",
            explanation: "«نفسه» تؤكد «الأبَ» المنصوب؛ فتحتاج الجملة «نَفْسَهُ» بالفتحة.",
          },
          {
            id: "genitive",
            sentence: "سَلَّمْتُ عَلَى الأَبِ {word}.",
            requiredForm: "نَفْسِهِ",
            role: "توكيد مجرور",
            explanation: "«نفسه» تؤكد «الأبِ» المجرور؛ فتحتاج الجملة «نَفْسِهِ» بالكسرة.",
          },
        ],
      },
      {
        id: "family-became-happy",
        topic: "كان وأخواتها",
        skill: "خبر أصبح منصوب",
        word: "سَعِيدَةً",
        correctChoiceId: "became",
        hint: "ابحث عن الفعل الناسخ «أصبحت» الذي ينصب الخبر.",
        choices: [
          {
            id: "nominal",
            sentence: "الأُسْرَةُ {word}.",
            requiredForm: "سَعِيدَةٌ",
            role: "خبر مرفوع",
            explanation: "هذه جملة اسمية بلا ناسخ؛ فالخبر مرفوع وتحتاج الجملة «سَعِيدَةٌ».",
          },
          {
            id: "inna",
            sentence: "إِنَّ الأُسْرَةَ {word}.",
            requiredForm: "سَعِيدَةٌ",
            role: "خبر إن مرفوع",
            explanation: "خبر «إنَّ» مرفوع؛ لذلك تحتاج الجملة «سَعِيدَةٌ» بالضمة.",
          },
          {
            id: "became",
            sentence: "أَصْبَحَتِ الأُسْرَةُ {word}.",
            requiredForm: "سَعِيدَةً",
            role: "خبر أصبح منصوب",
            explanation: "«أصبحت» من أخوات كان؛ تنصب الخبر، لذلك جاءت «سَعِيدَةً» بالفتحة.",
          },
        ],
      },
      {
        id: "khalid-substitute",
        topic: "البدل",
        skill: "البدل يتبع المبدل منه",
        word: "خَالِدٌ",
        correctChoiceId: "nominative",
        hint: "راقب حركة الاسم الذي يوضحه اسم «خالد».",
        choices: [
          {
            id: "accusative",
            sentence: "قَابَلْتُ صَدِيقَكَ {word}.",
            requiredForm: "خَالِدًا",
            role: "بدل منصوب",
            explanation: "«خالد» يوضح «صديقكَ» المنصوب؛ والبدل يتبع المبدل منه، فتحتاج الجملة «خَالِدًا».",
          },
          {
            id: "nominative",
            sentence: "حَضَرَ صَدِيقُكَ {word}.",
            requiredForm: "خَالِدٌ",
            role: "بدل مرفوع",
            explanation: "«خالد» يوضح «صديقُكَ» المرفوع؛ والبدل يتبعه في الرفع.",
          },
          {
            id: "genitive",
            sentence: "سَلَّمْتُ عَلَى صَدِيقِكَ {word}.",
            requiredForm: "خَالِدٍ",
            role: "بدل مجرور",
            explanation: "«خالد» يوضح «صديقِكَ» المجرور؛ فتحتاج الجملة «خَالِدٍ» بالكسرة.",
          },
        ],
      },
    ],
  };
